### ISSUE TITLE
Documentation link is down

### ISSUE THREAD

**Issue by TRINITRONIC** [CWKevo/pyflarum#3]
"There isn't a GitHub Pages site here."
It seems that your Github Pages repo has been deleted. Could you fix this? I really need the docs. Thank you!

**Comment by CWKevo** [comment]
https://freeflarum.com/docs

Works fine for me... What link are you using to access the page?

**Comment by CWKevo** [comment]
Indeed, thanks for reporting this, I'll fix it later today

**Comment by CWKevo** [comment]
It should be accessible again at https://cwkevo.github.io/pyflarum now, sorry for the downtime, I haven't had much time for this project recently due to lack of audience. But if you need any other help, open a new issue and I'll be happy to assist you!
